language: node_js

node_js:
  - '6'

before_install:
  - rvm install 2.2.3

before_script:
  - npm install -g gulp

  - gem install bundler
  - bundle install

script:
- bundle exec jekyll build
- gulp
- bundle exec rake site:deploy --quiet

env:
  global:
#  - GITHUB_REPO: "codeweeksi/codeweek.si"
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site/  # or remove this line to upload from root of repo
  github_token: $GH_TOKEN # Set in travis-ci.org dashboard
  target_branch: master
  fqdn: codeweek.si
  on:
    branch: source


