language: node_js

node_js:
  - '6'

before_install:
  - rvm install 2.2.3

before_script:
  - npm install -g gulp
  - gem install bundler
  - bundle install


script:
- bundle exec jekyll build
- gulp
- ./_script/deploy.sh

branches:
  only:
  - source

env:
  global:
#  - GITHUB_REPO: "codeweeksi/codeweek.si"
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

