language: node_js

node_js:
  - '6'

before_install:
  - rvm install 2.2.3

install:
- bundle install

before_script:
  - npm install -g gulp
  #- gem install bundler
  #- bundle install

script: 
- gulp
- bundle exec jekyll build
- bundle exec rake site:deploy --quiet


#script:
#- bundle exec jekyll build
#- gulp

branches:
  only:
  - source

env:
  global:
  - GITHUB_REPO: "codeweeksi/codeweek.si"
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

