name: Europe Code Week
markdown: kramdown
highlighter: rouge

# Using gulp, no need for sass part here
# sass:
#    sass_dir: _sass
#    style: :compressed

plugins_dir: 
  - jekyll-redirect-from

# GitHub
username:             Travis
repo:                 codeweek.si
branch:               source

# Revise these settings below every year

defaults:
  - scope:
      path: "" # all files in the project
    values:
      event_dates: "7.‐22. oktober 2018"
      event_year: "2018"

contact:
    email: katja.osljak@gmail.com
    twitter: CodeWeekEU
    facebook: codeEU
    github: codeeu

country-list: [austria, belgium, bulgaria, croatia, cyprus, czech_republic, denmark, estonia, finland, france, germany, greece, hungary, ireland, italy, kosovo, latvia, lithuania, luxembourg, malta, netherlands, poland, portugal, romania, slovakia, slovenia, spain, sweden, switzerland, united_kingdom]

description: A week to celebrate coding in Europe - Local site of Slovenia
url: http://codeweek.si


collections:
  - featured_events
  
keep_files:
  - assets
  
include: 
  - _pages

exclude:
  - lib
  - Gemfile
  - Gemfile.lock
  - node_modules
  - "*.sh"
  - gulpfile.js
  - package.json
  - deploy
  - vendor