name: Europe Code Week
markdown: redcarpet
pygments: true

contact:
    email: katja.osljak@gmail.com
    twitter: CodeWeekEU
    facebook: codeEU
    github: codeeu

country-list: [austria, belgium, bulgaria, croatia, cyprus, czech_republic, denmark, estonia, finland, france, germany, greece, hungary, ireland, italy, kosovo, latvia, lithuania, luxembourg, malta, netherlands, poland, portugal, romania, slovakia, slovenia, spain, sweden, switzerland, united_kingdom]

description: A week to celebrate coding in Europe - Local site of Slovenia
url: http://codeweek.si